baseURL = "https://github.com/tonycyriac/vestifex.git/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Vestifex Docs"
theme = "hugo-theme-techdoc"


[params]
    # Documentation Menu section
    # Menu style settings
    menu_style =  "slide-menu" 

  